import { Injectable } from '@angular/core';
import { Order } from 'app/models/order';

const orders: Order[] = [
  {
    id: '1',
    cupon: '432412',
    informe: 'KARINTO',
    tipoInforme: 'OR',
    tipoTramite: 'T1',
    calidad: 'A',
    fechaIngreso: '12/09/2023',
    fechaVencimiento: '19/09/2024',
    fechaVencimientoReal: '20/09/2024',
    fechaDescarga: '19/09/2024',
    estado: 'PENDIENTE',
    hasComment: true,
    comment: 'comentario 1',
    hasAttachments: false,
    attachments: [],
    abonado :{
      id : "1",
      nombre : "Abonado 1 ",
      codigo : "12345",
      revelarNombre : true,
      pais : "PERU",
      codigoPais : "pe",
      estado : "INACTIVO",
      nroReferencia : "1234546789",
      creditoConsultado : "1 000 000",
      indicaciones : "Aqui van las indicaciones",
      dtsAdicionales : "Datos adicionales"
    },
    creditoConsultado: 100000,
    numOrden: 10345,
    revelarNombre: 'NO',
    numeroReferencia: 23183012,
    indicacionesAbonado: 'Indicaciones del abonado aqui',

    //datos de la empresa
    nombreReal: 'KARINTO SA',
    nombreSolicitado: 'KARINTO ',
    continente: 'AMERICA',
    pais: 'PERU',
    ciudad: 'LIMA',
    regTributario: 'Regi. tributario ...',
    direccion: 'direccion de la empresa',
    telefono: '945848646',
    correo: 'karinto@example.com',
    fax: 'aqui va el fax ...',
    precioInforme: 50,
    fechaInforme: '10/06/2022',
  },
  {
    id: '2',
    cupon: '432413',
    informe: 'NESTLE',
    tipoInforme: 'RV',
    tipoTramite: 'T3',
    calidad: 'C',
    fechaIngreso: '22/07/2023',
    fechaVencimiento: '25/07/2023',
    fechaVencimientoReal: '26/07/2023',
    fechaDescarga: '26/07/2023',
    estado: 'ENVIADO',
    hasComment: true,
    comment: 'comentario 2',
    hasAttachments: true,
    attachments: [],
    abonado :{
      id : "1",
      nombre : "Abonado 1 Abonado Abonado",
      codigo : "12345",
      revelarNombre : true,
      pais : "PERU",
      codigoPais : "pe",
      estado : "INACTIVO",
      nroReferencia : "1234546789",
      creditoConsultado : "1 000 000",
      indicaciones : "Aqui van las indicaciones",
      dtsAdicionales : "Datos adicionales"
    },
    creditoConsultado: 100001,
    numOrden: 10345,
    revelarNombre: 'NO',
    numeroReferencia: 23183012,
    indicacionesAbonado: 'Indicaciones del abonado aqui',

    //datos de la empresa
    nombreReal: 'NESTLE SA',
    nombreSolicitado: 'NESTLE',
    continente: 'AMERICA',
    pais: 'PERU',
    ciudad: 'LIMA',
    regTributario: 'Regi. tributario ...',
    direccion: 'direccion de la empresa',
    telefono: '945848646',
    correo: 'nestle@example.com',
    fax: 'aqui va el fax ...',
    precioInforme: 50,
    fechaInforme: '10/06/2022',
  },
  {
    id: '3',
    cupon: '432414',
    informe: 'LAIVE',
    tipoInforme: 'RV',
    tipoTramite: 'T1',
    calidad: 'B',
    fechaIngreso: '12/09/2023',
    fechaVencimiento: '19/09/2023',
    fechaVencimientoReal: '20/09/2023',
    fechaDescarga: '19/09/2023',
    estado: 'ENV. VENCIDO',
    hasComment: false,
    comment: '',
    hasAttachments: false,
    attachments: [],
    abonado :{
      id : "3",
      nombre : "Abonado 3",
      codigo : "12347",
      revelarNombre : true,
      pais : "PERU",
      codigoPais : "pe",
      estado : "ACTIVO",
      nroReferencia : "1234546789",
      creditoConsultado : "1 000 000",
      indicaciones : "Aqui van las indicaciones",
      dtsAdicionales : "Datos adicionales"
    },
    creditoConsultado: 100002,
    numOrden: 10345,
    revelarNombre: 'NO',
    numeroReferencia: 23183012,
    indicacionesAbonado: 'Indicaciones del abonado aqui',

    //datos de la empresa
    nombreReal: 'LAIVE SA',
    nombreSolicitado: 'LAIVE',
    continente: 'AMERICA',
    pais: 'PERU',
    ciudad: 'LIMA',
    regTributario: 'Regi. tributario ...',
    direccion: 'direccion de la empresa',
    telefono: '945848646',
    correo: 'laive@example.com',
    fax: 'aqui va el fax ...',
    precioInforme: 50,
    fechaInforme: '10/06/2022',
  },
  {
    id: '4',
    cupon: '432415',
    informe: 'SAYON',
    tipoInforme: 'RV',
    tipoTramite: 'T3',
    calidad: 'B',
    fechaIngreso: '12/09/2023',
    fechaVencimiento: '19/09/2023',
    fechaVencimientoReal: '20/09/2023',
    fechaDescarga: '19/09/2023',
    estado: 'PENDIENTE',
    hasComment: false,
    comment: '',
    hasAttachments: false,
    attachments: [],
    abonado :{
      id : "4",
      nombre : "Abonado 4",
      codigo : "12348",
      revelarNombre : true,
      pais : "PERU",
      codigoPais : "pe",
      estado : "ACTIVO",
      nroReferencia : "1234546789",
      creditoConsultado : "1 000 000",
      indicaciones : "Aqui van las indicaciones",
      dtsAdicionales : "Datos adicionales"
    },
    creditoConsultado: 100003,
    numOrden: 10345,
    revelarNombre: 'NO',
    numeroReferencia: 23183012,
    indicacionesAbonado: 'Indicaciones del abonado aqui',

    //datos de la empresa
    nombreReal: 'SAYON SA',
    nombreSolicitado: 'SAYON ',
    continente: 'AMERICA',
    pais: 'PERU',
    ciudad: 'LIMA',
    regTributario: 'Regi. tributario ...',
    direccion: 'direccion de la empresa',
    telefono: '945848646',
    correo: 'sayon@example.com',
    fax: 'aqui va el fax ...',
    precioInforme: 50,
    fechaInforme: '10/06/2022',
  },
  {
    id: '5',
    cupon: '432416',
    informe: 'SAN JORGE',
    tipoInforme: 'OR',
    tipoTramite: 'T2',
    calidad: 'A',
    fechaIngreso: '12/09/2023',
    fechaVencimiento: '19/09/2023',
    fechaVencimientoReal: '20/09/2023',
    fechaDescarga: '19/09/2023',
    estado: 'PEND. VENCIDO',
    hasComment: true,
    comment: 'comentario 5',
    hasAttachments: false,
    attachments: [],
    abonado :{
      id : "3",
      nombre : "Abonado 3",
      codigo : "12347",
      revelarNombre : true,
      pais : "PERU",
      codigoPais : "pe",
      estado : "ACTIVO",
      nroReferencia : "1234546789",
      creditoConsultado : "1 000 000",
      indicaciones : "Aqui van las indicaciones",
      dtsAdicionales : "Datos adicionales"
    },
    creditoConsultado: 100004,
    numOrden: 10345,
    revelarNombre: 'NO',
    numeroReferencia: 23183012,
    indicacionesAbonado: 'Indicaciones del abonado aqui',

    //datos de la empresa
    nombreReal: 'SAN JORGE SAC',
    nombreSolicitado: 'SAN JORGE',
    continente: 'AMERICA',
    pais: 'PERU',
    ciudad: 'LIMA',
    regTributario: 'Regi. tributario ...',
    direccion: 'direccion de la empresa',
    telefono: '945848646',
    correo: 'san-jorge@example.com',
    fax: 'aqui va el fax ...',
    precioInforme: 50,
    fechaInforme: '10/06/2022',
  },
  {
    id: '6',
    cupon: '432417',
    informe: 'GLORIA',
    tipoInforme: 'RV',
    tipoTramite: 'T3',
    calidad: 'A',
    fechaIngreso: '12/08/2023',
    fechaVencimiento: '17/09/2023',
    fechaVencimientoReal: '18/09/2023',
    fechaDescarga: '21/09/2023',
    estado: 'ENVIADO',
    hasComment: false,
    comment: '',
    hasAttachments: true,
    attachments: [],
    abonado :{
      id : "4",
    nombre : "Abonado 4",
    codigo : "12348",
    revelarNombre : true,
    pais : "PERU",
    codigoPais : "pe",
    estado : "ACTIVO",
    nroReferencia : "1234546789",
    creditoConsultado : "1 000 000",
    indicaciones : "Aqui van las indicaciones",
    dtsAdicionales : "Datos adicionales"
    },
    creditoConsultado: 100005,
    numOrden: 10345,
    revelarNombre: 'NO',
    numeroReferencia: 23183012,
    indicacionesAbonado: 'Indicaciones del abonado aqui',

    //datos de la empresa
    nombreReal: 'GLORIA SA',
    nombreSolicitado: 'GLORIA ',
    continente: 'AMERICA',
    pais: 'PERU',
    ciudad: 'LIMA',
    regTributario: 'Regi. tributario ...',
    direccion: 'direccion de la empresa',
    telefono: '945848646',
    correo: 'gloria@example.com',
    fax: 'aqui va el fax ...',
    precioInforme: 50,
    fechaInforme: '10/06/2022',
  },
  {
    id: '7',
    cupon: '432418',
    informe: 'ALICORP',
    tipoInforme: 'RV',
    tipoTramite: 'T2',
    calidad: 'C',
    fechaIngreso: '09/09/2023',
    fechaVencimiento: '14/09/2023',
    fechaVencimientoReal: '15/09/2023',
    fechaDescarga: '22/09/2023',
    estado: 'ENV. VENCIDO',
    hasComment: false,
    comment: '',
    hasAttachments: false,
    attachments: [],
    abonado :{
      id : "5",
      nombre : "Abonado 5",
      codigo : "12349",
      revelarNombre : false,
      pais : "PERU",
      codigoPais : "pe",
      estado : "ACTIVO",
      nroReferencia : "1234546789",
      creditoConsultado : "1 000 000",
      indicaciones : "Aqui van las indicaciones",
      dtsAdicionales : "Datos adicionales"
    },
    creditoConsultado: 100006,
    numOrden: 10345,
    revelarNombre: 'NO',
    numeroReferencia: 23183012,
    indicacionesAbonado: 'Indicaciones del abonado aqui',

    //datos de la empresa
    nombreReal: 'ALICORP SA',
    nombreSolicitado: 'ALICORP ',
    continente: 'AMERICA',
    pais: 'PERU',
    ciudad: 'LIMA',
    regTributario: 'Regi. tributario ...',
    direccion: 'direccion de la empresa',
    telefono: '945848646',
    correo: 'alicorp@example.com',
    fax: 'aqui va el fax ...',
    precioInforme: 50,
    fechaInforme: '10/06/2022',
  },
];

@Injectable({
  providedIn: 'root',
})
export class OrderService {
  constructor() {}
  getOrders() {
    return orders;
  }
  getCommentByCupon(cupon: string) {
    return orders.filter((x) => x.cupon === cupon);
  }
}
