export interface Proveedor{
  id : number
  proveedor : string
  telefono : string
  pais : number
  calificacion : string
  fecha : string
  moneda : number
  credMaximo : string
  credMaximoIng : string
  plazos : string
  plazosIng : string
  cumplimiento : string
  clientesDesde : string
  clientesDesdeIng : string
  articulos : string
  articulosIng : string
  atendio : string
  comentarioAdicional : string
  comentarioAdicionalIng : string
  comentario : string
}
